#############################################
# Mosquitto Drop-in Config
#############################################
# logs verbose
log_type all

# TLS MQTT
listener 8884 0.0.0.0
protocol mqtt


# Server identity
cafile /opt/oqs-demos/certs/ca-cert.pem
certfile /opt/oqs-demos/certs/rsa-device-server-cert.pem
keyfile /opt/oqs-demos/certs/rsa-device-server-key.pem

# Enforce TLS group for TLS 1.3
tls_groups X25519MLKEM768

# Enable Client mTLS authentication
require_certificate true
use_identity_as_username true

allow_anonymous false

