server {

    listen 4433 ssl;

    ssl_certificate     /opt/oqs-demos/certs/pqc-device-cert.pem;
    ssl_certificate_key /opt/oqs-demos/certs/pqc-device-key.pem;

    ssl_protocols TLSv1.3;
    ssl_ecdh_curve kyber768:X25519MLKEM768;

    location / {
        root   /var/www/localhost/html;
        index  index.html index.htm;
    }
}
