server {

    listen 1433 ssl;

    ssl_certificate     /opt/oqs-demos/certs/rsa-device-cert.pem;
    ssl_certificate_key /opt/oqs-demos/certs/rsa-device-key.pem;

    ssl_protocols TLSv1.3;
    # use hybrid curve for key exchange
    ssl_ecdh_curve X25519MLKEM768;

    location / {
        root   /var/www/localhost/html;
        index  index.html index.htm;
    }
}
