server {

    listen 4433 ssl;

    ssl_certificate     /opt/oqs-demos/certs/pqc-device-cert.pem;
    ssl_certificate_key /opt/oqs-demos/certs/pqc-device-key.pem;

    ssl_protocols TLSv1.3;
    # use PQC only curve for key exchange (Note that this can be also be used with classical keys/certs)
    ssl_ecdh_curve mlkem768;

    location / {
        root   /var/www/localhost/html;
        index  index.html index.htm;
    }
}
